Repository Esri/arcgis-runtime-samples-ios, pull requests merged in 2020-09, with the labels that each got.

#952 Update: AGSRouteTrackerLocationDataSource in Navigate route
  arcgis-ios-sdk-samples/Route and directions/Navigate route/NavigateRoute.storyboard
  arcgis-ios-sdk-samples/Route and directions/Navigate route/NavigateRouteViewController.swift
  arcgis-ios-sdk-samples/Route and directions/Navigate route/README.md
  arcgis-ios-sdk-samples/Route and directions/Navigate route/README.metadata.json
  arcgis-ios-sdk-samples/Route and directions/Navigate route/navigate-route.png
Labels: enhancement

#965 Update: Spatial operations
  arcgis-ios-sdk-samples.xcodeproj/project.pbxproj
  arcgis-ios-sdk-samples/Geometry/Spatial operations/OperationsListViewController.swift
  arcgis-ios-sdk-samples/Geometry/Spatial operations/README.md
  arcgis-ios-sdk-samples/Geometry/Spatial operations/README.metadata.json
  arcgis-ios-sdk-samples/Geometry/Spatial operations/SpatialOperations.storyboard
  arcgis-ios-sdk-samples/Geometry/Spatial operations/SpatialOperationsViewController.swift
  arcgis-ios-sdk-samples/Geometry/Spatial operations/perform-spatial-operations.png
  arcgis-ios-sdk-samples/Geometry/Spatial operations/spatial-operations.png
Labels: enhancement

#967 Fix computed_accessors_order violation
  arcgis-ios-sdk-samples/Content Display Logic/Controllers/Color Picker/ColorPickerViewController.swift
Labels: linting

#961 New: Apply mosaic rule to rasters
  arcgis-ios-sdk-samples.xcodeproj/project.pbxproj
  arcgis-ios-sdk-samples/Content Display Logic/ContentPList.plist
  arcgis-ios-sdk-samples/Layers/Apply mosaic rule to rasters/ApplyMosaicRuleToRasters.storyboard
  arcgis-ios-sdk-samples/Layers/Apply mosaic rule to rasters/ApplyMosaicRuleToRastersViewController.swift
  arcgis-ios-sdk-samples/Layers/Apply mosaic rule to rasters/README.md
  arcgis-ios-sdk-samples/Layers/Apply mosaic rule to rasters/README.metadata.json
  arcgis-ios-sdk-samples/Layers/Apply mosaic rule to rasters/apply-mosaic-rule-to-rasters.png
Labels: high priority
